language: python
python:
  # Only 2.7 to prevent having to install NumPy and SciPy from source.
  - "2.7"

virtualenv:
  system_site_packages: true

install:
  - sudo apt-get update
  - sudo apt-get install cython python-numpy python-scipy
  - pip install scikit-learn
  - pip install .

script:
  - cd /tmp
  - nosetests --exe seqlearn
